//! 3W6HS firmware: one RP2040 (left half) scanning both keyboard halves.
//!
//! The left half is the GPIO matrix declared in `keyboard.toml` (`[matrix]`,
//! rows GP7–GP10, cols GP11–GP15). The right half sits behind a TCA9555 I/O
//! expander on I2C0 (SDA=GP0, SCL=GP1, address 0x20) and is scanned by
//! [`crate::right_matrix::Tca9555Matrix`], which publishes its events with a
//! row offset of 4 so the two halves tile the single 8×5 keymap grid.
//!
//! `#[rmk_keyboard]` still generates chip init, USB driver, storage/keymap,
//! keyboard, and the left matrix from `keyboard.toml`, but the generated
//! entry can only run that one matrix, so `#[Overwritten(entry)]` replaces
//! the final "start tasks" section: the expander bus and scanner are brought
//! up and every task runs under `rmk::run_all!`. `#[Overwritten(bind_interrupt)]`
//! adds the I2C0 interrupt binding the expander bus needs to the standard
//! USB/DMA ones.

#![no_main]
#![no_std]

mod right_matrix;

use rmk::macros::rmk_keyboard;

#[rmk_keyboard]
mod keyboard {
    use right_matrix::Tca9555Matrix;

    #[Overwritten(bind_interrupt)]
    fn irq_bindings() {
        use ::embassy_rp::bind_interrupts;

        bind_interrupts!(struct Irqs {
            // USB device controller (generated by rmk for every RP2040 board).
            USBCTRL_IRQ => ::embassy_rp::usb::InterruptHandler<::embassy_rp::peripherals::USB>;
            // DMA_CH0: free, DMA_CH1: storage flash.
            DMA_IRQ_0 => ::embassy_rp::dma::InterruptHandler<::embassy_rp::peripherals::DMA_CH0>, ::embassy_rp::dma::InterruptHandler<::embassy_rp::peripherals::DMA_CH1>;
            // I2C0: right-half TCA9555 expander.
            I2C0_IRQ => ::embassy_rp::i2c::InterruptHandler<::embassy_rp::peripherals::I2C0>;
        });
    }

    #[Overwritten(entry)]
    async fn run() {
        // Right half on I2C0: SCL = GP1, SDA = GP0, expander at 0x20.
        let right_i2c = ::embassy_rp::i2c::I2c::new_async(
            p.I2C0,
            p.PIN_1,
            p.PIN_0,
            Irqs,
            ::embassy_rp::i2c::Config::default(),
        );
        let right_debouncer = ::rmk::debounce::fast_debouncer::FastDebouncer::<4, 5>::new();
        let mut right_matrix = Tca9555Matrix::<_, _, 4, 5>::new(right_i2c, right_debouncer);

        // With the entry overridden, the transport prelude is not generated:
        // build the USB transport and the WPM processor here (no host service:
        // Vial and Rynk are both disabled).
        let mut wpm_processor = ::rmk::processor::builtin::wpm::WpmProcessor::new();
        let mut usb_transport = ::rmk::usb::UsbTransport::new(driver, rmk_config.device_config);

        ::rmk::run_all!(
            matrix,
            right_matrix,
            keyboard,
            storage,
            usb_transport,
            wpm_processor
        )
        .await;
    }
}
